spring:
  redis:
    cluster:
      #集群节点IP:port,IP:port
      nodes: 192.168.2.128:7000,192.168.2.128:7001,192.168.2.128:7002,192.168.2.128:7003,192.168.2.128:7004,192.168.2.128:7005
    database: 0
    password: 123456
    # 连接超时，后面要加上单位，否则报错
    timeout: 5s
    lettuce:
      pool:
        # 连接池最大连接数（负数表示无限制）
        max-active: 200
        # 连接池最大空闲连接数
        max-idle: 8
        # 连接池最小空闲连接数
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

#自定义缓存配置，custom-cache名称固定，testA为自定义cache
damon:
  cache:
    custom-cache:
      #testA对应@Cacheable的value
      testA:
        #缓存的超时时间
        time-to-live: 400s
        #默认@Cacheable的value与对象key之间的连接符是::，此处可以自定义连接符
        key-prefix: ^
      testB:
        time-to-live: 500s
        #key-prefix: \!
        #use-key-prefix: false
        cache-null-values: false